{
  "uid" : "3d328564dccde1c",
  "name" : "Unsuccessful login",
  "fullName" : "tests.test_index_page#test_unsuccessful_login",
  "historyId" : "c8af2a131b02258090acaa95b6d362a5",
  "time" : {
    "start" : 1703963707618,
    "stop" : 1703963707791,
    "duration" : 173
  },
  "description" : "Unsuccess login",
  "descriptionHtml" : "<p>Unsuccess login</p>\n",
  "status" : "failed",
  "statusMessage" : "AssertionError: expected txt: Username field cannot be emp2ty, but actual txt: Username field cannot be empty",
  "statusTrace" : "index_page_instance = <pages.index_page.IndexPage object at 0x7fe9f4639f00>\nun_login = '', un_password = 'correct_username'\nun_text = 'Username field cannot be emp2ty'\n\n    @allure.description('Unsuccess login')\n    @allure.label('owner', 'Sergey')\n    @allure.title('Unsuccessful login')\n    @allure.suite('Authorization suite')\n    @mark.index\n    @pytest.mark.parametrize('un_login, un_password, un_text', (incorrect_1, incorrect_2, incorrect_3, incorrect_4))\n    def test_unsuccessful_login(index_page_instance, un_login, un_password, un_text):\n        index_page_instance.enter_username(un_login)\n        index_page_instance.enter_password(un_password)\n        index_page_instance.click_to_login_btn()\n>       index_page_instance.verify_incorrect_login(un_text)\n\ntests/test_index_page.py:36: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \npages/index_page.py:45: in verify_incorrect_login\n    self.assert_equal(self.get_text(self.ERROR_TEXT), expected=text)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nactual = 'Username field cannot be empty'\nexpected = 'Username field cannot be emp2ty'\n\n    @staticmethod\n    def assert_equal(actual, expected):\n>       assert actual == expected, AssertionsErrors.ERROR_EQUAL.format(expected, actual)\nE       AssertionError: expected txt: Username field cannot be emp2ty, but actual txt: Username field cannot be empty\n\nsupport/assertions.py:7: AssertionError",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ {
    "name" : "get_chrome_options",
    "time" : {
      "start" : 1703963706698,
      "stop" : 1703963706698,
      "duration" : 0
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  }, {
    "name" : "index_page_instance",
    "time" : {
      "start" : 1703963707499,
      "stop" : 1703963707617,
      "duration" : 118
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  }, {
    "name" : "screenshot_on_failures",
    "time" : {
      "start" : 1703963707498,
      "stop" : 1703963707498,
      "duration" : 0
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  }, {
    "name" : "get_webdriver",
    "time" : {
      "start" : 1703963706698,
      "stop" : 1703963707498,
      "duration" : 800
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  } ],
  "testStage" : {
    "description" : "Unsuccess login",
    "status" : "failed",
    "statusMessage" : "AssertionError: expected txt: Username field cannot be emp2ty, but actual txt: Username field cannot be empty",
    "statusTrace" : "index_page_instance = <pages.index_page.IndexPage object at 0x7fe9f4639f00>\nun_login = '', un_password = 'correct_username'\nun_text = 'Username field cannot be emp2ty'\n\n    @allure.description('Unsuccess login')\n    @allure.label('owner', 'Sergey')\n    @allure.title('Unsuccessful login')\n    @allure.suite('Authorization suite')\n    @mark.index\n    @pytest.mark.parametrize('un_login, un_password, un_text', (incorrect_1, incorrect_2, incorrect_3, incorrect_4))\n    def test_unsuccessful_login(index_page_instance, un_login, un_password, un_text):\n        index_page_instance.enter_username(un_login)\n        index_page_instance.enter_password(un_password)\n        index_page_instance.click_to_login_btn()\n>       index_page_instance.verify_incorrect_login(un_text)\n\ntests/test_index_page.py:36: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \npages/index_page.py:45: in verify_incorrect_login\n    self.assert_equal(self.get_text(self.ERROR_TEXT), expected=text)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nactual = 'Username field cannot be empty'\nexpected = 'Username field cannot be emp2ty'\n\n    @staticmethod\n    def assert_equal(actual, expected):\n>       assert actual == expected, AssertionsErrors.ERROR_EQUAL.format(expected, actual)\nE       AssertionError: expected txt: Username field cannot be emp2ty, but actual txt: Username field cannot be empty\n\nsupport/assertions.py:7: AssertionError",
    "steps" : [ {
      "name" : "ввели логин",
      "time" : {
        "start" : 1703963707618,
        "stop" : 1703963707673,
        "duration" : 55
      },
      "status" : "passed",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ {
        "name" : "login",
        "value" : "''"
      } ],
      "stepsCount" : 0,
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : false,
      "hasContent" : true
    }, {
      "name" : "ввели пароль",
      "time" : {
        "start" : 1703963707673,
        "stop" : 1703963707724,
        "duration" : 51
      },
      "status" : "passed",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ {
        "name" : "password",
        "value" : "'correct_username'"
      } ],
      "stepsCount" : 0,
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : false,
      "hasContent" : true
    }, {
      "name" : "нажали на кнопку логина",
      "time" : {
        "start" : 1703963707724,
        "stop" : 1703963707766,
        "duration" : 42
      },
      "status" : "passed",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ ],
      "stepsCount" : 0,
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : false,
      "hasContent" : false
    }, {
      "name" : "проверка соответствия ошибки авторизации",
      "time" : {
        "start" : 1703963707767,
        "stop" : 1703963707791,
        "duration" : 24
      },
      "status" : "failed",
      "statusMessage" : "AssertionError: expected txt: Username field cannot be emp2ty, but actual txt: Username field cannot be empty\n",
      "statusTrace" : "  File \"/home/runner/.local/lib/python3.10/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n  File \"/home/runner/work/test-automation/test-automation/pages/index_page.py\", line 45, in verify_incorrect_login\n    self.assert_equal(self.get_text(self.ERROR_TEXT), expected=text)\n  File \"/home/runner/work/test-automation/test-automation/support/assertions.py\", line 7, in assert_equal\n    assert actual == expected, AssertionsErrors.ERROR_EQUAL.format(expected, actual)\n",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ {
        "name" : "text",
        "value" : "'Username field cannot be emp2ty'"
      } ],
      "stepsCount" : 0,
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : true,
      "hasContent" : true
    } ],
    "attachments" : [ {
      "uid" : "395fe97d8145585c",
      "name" : "log",
      "source" : "395fe97d8145585c.txt",
      "type" : "text/plain",
      "size" : 1368
    } ],
    "parameters" : [ ],
    "stepsCount" : 4,
    "attachmentsCount" : 1,
    "shouldDisplayMessage" : true,
    "hasContent" : true
  },
  "afterStages" : [ {
    "name" : "index_page_instance::0",
    "time" : {
      "start" : 1703963707795,
      "stop" : 1703963707852,
      "duration" : 57
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  }, {
    "name" : "screenshot_on_failures::0",
    "time" : {
      "start" : 1703963707852,
      "stop" : 1703963707854,
      "duration" : 2
    },
    "status" : "broken",
    "statusMessage" : "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=39013): Max retries exceeded with url: /session/8a31a8527cfbeb15dd8e5e6b720c44fc/screenshot (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe9f46394e0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
    "statusTrace" : "  File \"/home/runner/.local/lib/python3.10/site-packages/allure_commons/_allure.py\", line 221, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"/home/runner/.local/lib/python3.10/site-packages/_pytest/fixtures.py\", line 911, in _teardown_yield_fixture\n    next(it)\n  File \"/home/runner/work/test-automation/test-automation/conftest.py\", line 97, in screenshot_on_failures\n    get_webdriver.get_screenshot_as_file(screenshot)\n  File \"/home/runner/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 805, in get_screenshot_as_file\n    png = self.get_screenshot_as_png()\n  File \"/home/runner/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 839, in get_screenshot_as_png\n    return b64decode(self.get_screenshot_as_base64().encode(\"ascii\"))\n  File \"/home/runner/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 850, in get_screenshot_as_base64\n    return self.execute(Command.SCREENSHOT)[\"value\"]\n  File \"/home/runner/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 346, in execute\n    response = self.command_executor.execute(driver_command, params)\n  File \"/home/runner/.local/lib/python3.10/site-packages/selenium/webdriver/remote/remote_connection.py\", line 300, in execute\n    return self._request(command_info[0], url, body=data)\n  File \"/home/runner/.local/lib/python3.10/site-packages/selenium/webdriver/remote/remote_connection.py\", line 321, in _request\n    response = self._conn.request(method, url, body=body, headers=headers)\n  File \"/usr/lib/python3/dist-packages/urllib3/request.py\", line 74, in request\n    return self.request_encode_url(\n  File \"/usr/lib/python3/dist-packages/urllib3/request.py\", line 96, in request_encode_url\n    return self.urlopen(method, url, **extra_kw)\n  File \"/usr/lib/python3/dist-packages/urllib3/poolmanager.py\", line 375, in urlopen\n    response = conn.urlopen(method, u.request_uri, **kw)\n  File \"/usr/lib/python3/dist-packages/urllib3/connectionpool.py\", line 784, in urlopen\n    return self.urlopen(\n  File \"/usr/lib/python3/dist-packages/urllib3/connectionpool.py\", line 784, in urlopen\n    return self.urlopen(\n  File \"/usr/lib/python3/dist-packages/urllib3/connectionpool.py\", line 784, in urlopen\n    return self.urlopen(\n  File \"/usr/lib/python3/dist-packages/urllib3/connectionpool.py\", line 756, in urlopen\n    retries = retries.increment(\n  File \"/usr/lib/python3/dist-packages/urllib3/util/retry.py\", line 574, in increment\n    raise MaxRetryError(_pool, url, error or ResponseError(cause))\n",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : true,
    "hasContent" : true
  } ],
  "labels" : [ {
    "name" : "owner",
    "value" : "Sergey"
  }, {
    "name" : "suite",
    "value" : "Authorization suite"
  }, {
    "name" : "tag",
    "value" : "index"
  }, {
    "name" : "parentSuite",
    "value" : "tests"
  }, {
    "name" : "host",
    "value" : "fv-az532-920"
  }, {
    "name" : "thread",
    "value" : "4152-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "tests.test_index_page"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ {
    "name" : "un_login",
    "value" : "''"
  }, {
    "name" : "un_password",
    "value" : "'correct_username'"
  }, {
    "name" : "un_text",
    "value" : "'Username field cannot be emp2ty'"
  } ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "owner" : "Sergey",
    "retries" : [ ],
    "categories" : [ {
      "name" : "Product defects",
      "matchedStatuses" : [ ],
      "flaky" : false
    } ],
    "tags" : [ "index" ]
  },
  "source" : "3d328564dccde1c.json",
  "parameterValues" : [ "''", "'correct_username'", "'Username field cannot be emp2ty'" ]
}